import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import ToastProvider from "@/components/providers/toaster-provider";
import AuthSessionProvider from "@/components/providers/session-provider";
import StoreProvider from "@/components/providers/redux-provider";

const caveat = Caveat({
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={caveat.className}>
          <div>
            <AuthSessionProvider>
              <ToastProvider />
              <Navbar />
              {children}
            </AuthSessionProvider>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
