import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "./(routes)/(root)/_components/navbar";

const caveat = Caveat({
  subsets: ["latin"],
  weight: "700"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={caveat.className}>
        <div>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
