import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";
import Navbar from "./(routes)/(root)/_components/navbar";
import { cn } from "@/lib/utils";
import ToastProvider from "@/components/providers/toaster-provider";
import AuthSessionProvider from "@/components/providers/session-provider";

const caveat = Caveat({
  subsets: ["latin"],
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;

}) {
  return (
    <html lang="en">
      <body className={cn(caveat.className)}>
        <div>
          <AuthSessionProvider >
            <ToastProvider />
            <Navbar />
            {children}
          </AuthSessionProvider>
        </div>
      </body>
    </html>
  );
}
